#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'examples-tf2-py==0.12.5','console_scripts','static_broadcaster'
__requires__ = 'examples-tf2-py==0.12.5'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('examples-tf2-py==0.12.5', 'console_scripts', 'static_broadcaster')()
    )
